# coding: utf-8

# flake8: noqa

"""
    Gate API v4

    Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.  # noqa: E501

    Contact: support@mail.gate.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "4.51.0"

# import apis into sdk package
from src.exchange.gateio.github.gate_api.api.earn_uni_api import EarnUniApi
from src.exchange.gateio.github.gate_api.api.margin_uni_api import MarginUniApi
from src.exchange.gateio.github.gate_api.api.portfolio_api import PortfolioApi
from src.exchange.gateio.github.gate_api.api.sub_account_api import SubAccountApi
from src.exchange.gateio.github.gate_api.api.account_api import AccountApi
from src.exchange.gateio.github.gate_api.api.delivery_api import DeliveryApi
from src.exchange.gateio.github.gate_api.api.flash_swap_api import FlashSwapApi
from src.exchange.gateio.github.gate_api.api.futures_api import FuturesApi
from src.exchange.gateio.github.gate_api.api.margin_api import MarginApi
from src.exchange.gateio.github.gate_api.api.options_api import OptionsApi
from src.exchange.gateio.github.gate_api.api.rebate_api import RebateApi
from src.exchange.gateio.github.gate_api.api.spot_api import SpotApi
from src.exchange.gateio.github.gate_api.api.wallet_api import WalletApi
from src.exchange.gateio.github.gate_api.api.withdrawal_api import WithdrawalApi

# import ApiClient
from src.exchange.gateio.github.gate_api.api_client import ApiClient
from src.exchange.gateio.github.gate_api.configuration import Configuration
from src.exchange.gateio.github.gate_api.exceptions import OpenApiException
from src.exchange.gateio.github.gate_api.exceptions import ApiTypeError
from src.exchange.gateio.github.gate_api.exceptions import ApiValueError
from src.exchange.gateio.github.gate_api.exceptions import ApiKeyError
from src.exchange.gateio.github.gate_api.exceptions import ApiException

# import models into sdk package
from src.exchange.gateio.github.gate_api.models.account_balance import AccountBalance
from src.exchange.gateio.github.gate_api.models.account_detail import AccountDetail
from src.exchange.gateio.github.gate_api.models.account_detail_key import AccountDetailKey
from src.exchange.gateio.github.gate_api.models.agency_commission import AgencyCommission
from src.exchange.gateio.github.gate_api.models.agency_commission_history import AgencyCommissionHistory
from src.exchange.gateio.github.gate_api.models.agency_transaction import AgencyTransaction
from src.exchange.gateio.github.gate_api.models.agency_transaction_history import AgencyTransactionHistory
from src.exchange.gateio.github.gate_api.models.api_v4_key_perm import ApiV4KeyPerm
from src.exchange.gateio.github.gate_api.models.auto_repay_setting import AutoRepaySetting
from src.exchange.gateio.github.gate_api.models.batch_futures_order import BatchFuturesOrder
from src.exchange.gateio.github.gate_api.models.batch_order import BatchOrder
from src.exchange.gateio.github.gate_api.models.cancel_batch_order import CancelBatchOrder
from src.exchange.gateio.github.gate_api.models.cancel_order_result import CancelOrderResult
from src.exchange.gateio.github.gate_api.models.contract import Contract
from src.exchange.gateio.github.gate_api.models.contract_stat import ContractStat
from src.exchange.gateio.github.gate_api.models.countdown_cancel_all_futures_task import CountdownCancelAllFuturesTask
from src.exchange.gateio.github.gate_api.models.countdown_cancel_all_spot_task import CountdownCancelAllSpotTask
from src.exchange.gateio.github.gate_api.models.create_portfolio_spot_order import CreatePortfolioSpotOrder
from src.exchange.gateio.github.gate_api.models.create_uni_lend import CreateUniLend
from src.exchange.gateio.github.gate_api.models.create_uni_loan import CreateUniLoan
from src.exchange.gateio.github.gate_api.models.cross_margin_account import CrossMarginAccount
from src.exchange.gateio.github.gate_api.models.cross_margin_account_book import CrossMarginAccountBook
from src.exchange.gateio.github.gate_api.models.cross_margin_balance import CrossMarginBalance
from src.exchange.gateio.github.gate_api.models.cross_margin_balance1 import CrossMarginBalance1
from src.exchange.gateio.github.gate_api.models.cross_margin_currency import CrossMarginCurrency
from src.exchange.gateio.github.gate_api.models.cross_margin_loan import CrossMarginLoan
from src.exchange.gateio.github.gate_api.models.cross_margin_repay_request import CrossMarginRepayRequest
from src.exchange.gateio.github.gate_api.models.cross_margin_repayment import CrossMarginRepayment
from src.exchange.gateio.github.gate_api.models.cross_margin_transferable import CrossMarginTransferable
from src.exchange.gateio.github.gate_api.models.currency import Currency
from src.exchange.gateio.github.gate_api.models.currency_chain import CurrencyChain
from src.exchange.gateio.github.gate_api.models.currency_pair import CurrencyPair
from src.exchange.gateio.github.gate_api.models.delivery_candlestick import DeliveryCandlestick
from src.exchange.gateio.github.gate_api.models.delivery_contract import DeliveryContract
from src.exchange.gateio.github.gate_api.models.delivery_settlement import DeliverySettlement
from src.exchange.gateio.github.gate_api.models.deposit_address import DepositAddress
from src.exchange.gateio.github.gate_api.models.flash_swap_currency import FlashSwapCurrency
from src.exchange.gateio.github.gate_api.models.flash_swap_currency_pair import FlashSwapCurrencyPair
from src.exchange.gateio.github.gate_api.models.flash_swap_order import FlashSwapOrder
from src.exchange.gateio.github.gate_api.models.flash_swap_order_preview import FlashSwapOrderPreview
from src.exchange.gateio.github.gate_api.models.flash_swap_order_request import FlashSwapOrderRequest
from src.exchange.gateio.github.gate_api.models.flash_swap_preview_request import FlashSwapPreviewRequest
from src.exchange.gateio.github.gate_api.models.funding_account import FundingAccount
from src.exchange.gateio.github.gate_api.models.funding_book_item import FundingBookItem
from src.exchange.gateio.github.gate_api.models.funding_rate_record import FundingRateRecord
from src.exchange.gateio.github.gate_api.models.futures_account import FuturesAccount
from src.exchange.gateio.github.gate_api.models.futures_account_book import FuturesAccountBook
from src.exchange.gateio.github.gate_api.models.futures_account_history import FuturesAccountHistory
from src.exchange.gateio.github.gate_api.models.futures_auto_deleverage import FuturesAutoDeleverage
from src.exchange.gateio.github.gate_api.models.futures_candlestick import FuturesCandlestick
from src.exchange.gateio.github.gate_api.models.futures_fee import FuturesFee
from src.exchange.gateio.github.gate_api.models.futures_index_constituents import FuturesIndexConstituents
from src.exchange.gateio.github.gate_api.models.futures_initial_order import FuturesInitialOrder
from src.exchange.gateio.github.gate_api.models.futures_liq_order import FuturesLiqOrder
from src.exchange.gateio.github.gate_api.models.futures_liquidate import FuturesLiquidate
from src.exchange.gateio.github.gate_api.models.futures_order import FuturesOrder
from src.exchange.gateio.github.gate_api.models.futures_order_amendment import FuturesOrderAmendment
from src.exchange.gateio.github.gate_api.models.futures_order_book import FuturesOrderBook
from src.exchange.gateio.github.gate_api.models.futures_order_book_item import FuturesOrderBookItem
from src.exchange.gateio.github.gate_api.models.futures_premium_index import FuturesPremiumIndex
from src.exchange.gateio.github.gate_api.models.futures_price_trigger import FuturesPriceTrigger
from src.exchange.gateio.github.gate_api.models.futures_price_triggered_order import FuturesPriceTriggeredOrder
from src.exchange.gateio.github.gate_api.models.futures_ticker import FuturesTicker
from src.exchange.gateio.github.gate_api.models.futures_trade import FuturesTrade
from src.exchange.gateio.github.gate_api.models.index_constituent import IndexConstituent
from src.exchange.gateio.github.gate_api.models.insurance_record import InsuranceRecord
from src.exchange.gateio.github.gate_api.models.ledger_record import LedgerRecord
from src.exchange.gateio.github.gate_api.models.liquidate_order import LiquidateOrder
from src.exchange.gateio.github.gate_api.models.loan import Loan
from src.exchange.gateio.github.gate_api.models.loan_patch import LoanPatch
from src.exchange.gateio.github.gate_api.models.loan_record import LoanRecord
from src.exchange.gateio.github.gate_api.models.margin_account import MarginAccount
from src.exchange.gateio.github.gate_api.models.margin_account_book import MarginAccountBook
from src.exchange.gateio.github.gate_api.models.margin_account_currency import MarginAccountCurrency
from src.exchange.gateio.github.gate_api.models.margin_borrowable import MarginBorrowable
from src.exchange.gateio.github.gate_api.models.margin_currency_pair import MarginCurrencyPair
from src.exchange.gateio.github.gate_api.models.margin_transferable import MarginTransferable
from src.exchange.gateio.github.gate_api.models.max_uni_borrowable import MaxUniBorrowable
from src.exchange.gateio.github.gate_api.models.multi_chain_address_item import MultiChainAddressItem
from src.exchange.gateio.github.gate_api.models.my_futures_trade import MyFuturesTrade
from src.exchange.gateio.github.gate_api.models.my_futures_trade_time_range import MyFuturesTradeTimeRange
from src.exchange.gateio.github.gate_api.models.open_orders import OpenOrders
from src.exchange.gateio.github.gate_api.models.options_account import OptionsAccount
from src.exchange.gateio.github.gate_api.models.options_account_book import OptionsAccountBook
from src.exchange.gateio.github.gate_api.models.options_candlestick import OptionsCandlestick
from src.exchange.gateio.github.gate_api.models.options_contract import OptionsContract
from src.exchange.gateio.github.gate_api.models.options_my_settlements import OptionsMySettlements
from src.exchange.gateio.github.gate_api.models.options_my_trade import OptionsMyTrade
from src.exchange.gateio.github.gate_api.models.options_order import OptionsOrder
from src.exchange.gateio.github.gate_api.models.options_position import OptionsPosition
from src.exchange.gateio.github.gate_api.models.options_position_close import OptionsPositionClose
from src.exchange.gateio.github.gate_api.models.options_position_close_order import OptionsPositionCloseOrder
from src.exchange.gateio.github.gate_api.models.options_settlement import OptionsSettlement
from src.exchange.gateio.github.gate_api.models.options_ticker import OptionsTicker
from src.exchange.gateio.github.gate_api.models.options_underlying import OptionsUnderlying
from src.exchange.gateio.github.gate_api.models.options_underlying_ticker import OptionsUnderlyingTicker
from src.exchange.gateio.github.gate_api.models.order import Order
from src.exchange.gateio.github.gate_api.models.order_book import OrderBook
from src.exchange.gateio.github.gate_api.models.order_patch import OrderPatch
from src.exchange.gateio.github.gate_api.models.patch_uni_lend import PatchUniLend
from src.exchange.gateio.github.gate_api.models.portfolio_account import PortfolioAccount
from src.exchange.gateio.github.gate_api.models.portfolio_borrowable import PortfolioBorrowable
from src.exchange.gateio.github.gate_api.models.portfolio_loan import PortfolioLoan
from src.exchange.gateio.github.gate_api.models.portfolio_loan_record import PortfolioLoanRecord
from src.exchange.gateio.github.gate_api.models.portfolio_margin_balance import PortfolioMarginBalance
from src.exchange.gateio.github.gate_api.models.portfolio_spot_orders import PortfolioSpotOrders
from src.exchange.gateio.github.gate_api.models.portfolio_transferable import PortfolioTransferable
from src.exchange.gateio.github.gate_api.models.position import Position
from src.exchange.gateio.github.gate_api.models.position_close import PositionClose
from src.exchange.gateio.github.gate_api.models.position_close_order import PositionCloseOrder
from src.exchange.gateio.github.gate_api.models.repay_request import RepayRequest
from src.exchange.gateio.github.gate_api.models.repayment import Repayment
from src.exchange.gateio.github.gate_api.models.saved_address import SavedAddress
from src.exchange.gateio.github.gate_api.models.spot_account import SpotAccount
from src.exchange.gateio.github.gate_api.models.spot_account_book import SpotAccountBook
from src.exchange.gateio.github.gate_api.models.spot_fee import SpotFee
from src.exchange.gateio.github.gate_api.models.spot_price_put_order import SpotPricePutOrder
from src.exchange.gateio.github.gate_api.models.spot_price_trigger import SpotPriceTrigger
from src.exchange.gateio.github.gate_api.models.spot_price_triggered_order import SpotPriceTriggeredOrder
from src.exchange.gateio.github.gate_api.models.stp_group import StpGroup
from src.exchange.gateio.github.gate_api.models.stp_group_user import StpGroupUser
from src.exchange.gateio.github.gate_api.models.sub_account import SubAccount
from src.exchange.gateio.github.gate_api.models.sub_account_balance import SubAccountBalance
from src.exchange.gateio.github.gate_api.models.sub_account_cross_margin_balance import SubAccountCrossMarginBalance
from src.exchange.gateio.github.gate_api.models.sub_account_futures_balance import SubAccountFuturesBalance
from src.exchange.gateio.github.gate_api.models.sub_account_key import SubAccountKey
from src.exchange.gateio.github.gate_api.models.sub_account_margin_balance import SubAccountMarginBalance
from src.exchange.gateio.github.gate_api.models.sub_account_to_sub_account import SubAccountToSubAccount
from src.exchange.gateio.github.gate_api.models.sub_account_transfer import SubAccountTransfer
from src.exchange.gateio.github.gate_api.models.sub_cross_margin_account import SubCrossMarginAccount
from src.exchange.gateio.github.gate_api.models.system_time import SystemTime
from src.exchange.gateio.github.gate_api.models.ticker import Ticker
from src.exchange.gateio.github.gate_api.models.total_balance import TotalBalance
from src.exchange.gateio.github.gate_api.models.trade import Trade
from src.exchange.gateio.github.gate_api.models.trade_fee import TradeFee
from src.exchange.gateio.github.gate_api.models.transaction_id import TransactionID
from src.exchange.gateio.github.gate_api.models.transfer import Transfer
from src.exchange.gateio.github.gate_api.models.trigger_order_response import TriggerOrderResponse
from src.exchange.gateio.github.gate_api.models.trigger_time import TriggerTime
from src.exchange.gateio.github.gate_api.models.uni_currency import UniCurrency
from src.exchange.gateio.github.gate_api.models.uni_currency_pair import UniCurrencyPair
from src.exchange.gateio.github.gate_api.models.uni_interest_record import UniInterestRecord
from src.exchange.gateio.github.gate_api.models.uni_lend import UniLend
from src.exchange.gateio.github.gate_api.models.uni_lend_interest import UniLendInterest
from src.exchange.gateio.github.gate_api.models.uni_lend_record import UniLendRecord
from src.exchange.gateio.github.gate_api.models.uni_loan import UniLoan
from src.exchange.gateio.github.gate_api.models.uni_loan_interest_record import UniLoanInterestRecord
from src.exchange.gateio.github.gate_api.models.uni_loan_record import UniLoanRecord
from src.exchange.gateio.github.gate_api.models.withdraw_status import WithdrawStatus
